<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit38caf34d8413f6bb66a4f9f66d8975cf
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit38caf34d8413f6bb66a4f9f66d8975cf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit38caf34d8413f6bb66a4f9f66d8975cf::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
